name: build_and_deploy_arm64

on:
  # Allow to run the workflow manually from Actions tab
  workflow_dispatch:
    inputs:
      baseversion:
        description: 'Image base version'
        required: true
        default: '0.9'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: tnedd/raspisysmon
      DOCKER_TARGET_PLATFORM: linux/arm/v8
    steps:
      - 
        name: Checkout repo
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Prepare
        if: success()
        id: prepare
        run: |
          echo ::set-output name=docker_platform::$DOCKER_TARGET_PLATFORM
          echo ::set-output name=docker_image::$DOCKER_IMAGE
          echo ::set-output name=version::${{ github.event.inputs.baseversion }}.$GITHUB_RUN_NUMBER
      -
        name: Log into registry docker hub
        if: |
          success() && 
          github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Build docker image
        if: success()
        working-directory: .
        run: |
          docker buildx build . \
            --platform ${{ steps.prepare.outputs.docker_platform }} \
            --file ../dockerfiles/arm64.Dockerfile \
            --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }} \
            --output type=image,push=true